### ISSUE TITLE
Fix project coding style

### ISSUE THREAD

**Issue by afanasy** [akura-co/stebeneva.ru#21]
- https://docs.npmjs.com/misc/coding-style
- https://github.com/felixge/node-style-guide
- no semicolons
- commas last (if there is a list of things separated by commas, and it wraps across multiple lines, put the comma at the start of the next line)
- spaces in JSON after `:`, otherwise no spaces
- methods chaining dot last
- one line ternary operator is ok
- not naming closures is ok
- nested closures are ok

**Comment by afanasy** [comment]
thanks! please, put commas last

**Comment by raabbajam** [comment]
@afanasy I am confused, which one is it? `commas last` or `put the comma at the start of the next line` ?

**Comment by afanasy** [comment]
manually written rules overwrite those from links, so commas last
